### Configure PyTorch CUDA memory allocation settings to prevent fragmentation

In [ ]:
 import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True,max_split_size_mb:128"

### Check GPU availability and display GPU information

In [1]:
gpu_info = !nvidia-smi
gpu_info = "\n".join(gpu_info)
if gpu_info.find("failed") >= 0:
    print("Not connected to a GPU")
else:
    print(gpu_info)

Sun Apr  5 14:37:03 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   29C    P0             44W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

### Install required Python packages (datasets, transformers, torchaudio, jiwer, accelerate, evaluate)

In [2]:
 %%capture
!pip install datasets==3.6.0
!pip install transformers==4.57.1
!pip install torchaudio
!pip install jiwer
!pip install accelerate -U
!pip install evaluate

### Install system dependencies and clone the KenLM language model toolkit

In [3]:
!sudo apt-get update
!sudo apt-get install build-essential libboost-all-dev cmake zlib1g-dev libbz2-dev liblzma-dev
!sudo apt-get install libboost-all-dev libeigen3-dev
!git clone https://github.com/kpu/kenlm
%cd kenlm
!pip install e .

Hit:1 https://cli.github.com/packages stable InRelease
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,980 kB]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:10 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,482 kB]
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,960 kB]
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,310 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,219 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,844 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,622 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,125 kB]
Fetched 33.9 MB in 3s (12.9 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
libbz2-dev is already the newest version (1.0.8-5build1).
libbz2-dev set to manually installed.
liblzma-dev is already the newest version (5.2.5-2ubuntu1).
liblzma-dev set to manually installed.
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu9.2).
zlib1g-dev set to manually installed.
The following additional packages will be installed:
  javascript-common libboost-atomic-dev libboost-atomic1.74-dev
  libboost-atomic1.74.0 libboost-chrono-dev libboost-chrono1.74-dev
  libboost-chrono1.74.0 libboost-container-dev libboost-container1.74-dev
  libboost-container1.74.0 libboost-context-dev libboost-context1.74-dev
  libboost-context1.74.0 libboost-coroutine-dev libboost-coroutine1.74-dev
  libboost-coroutine1.74.0 libboost-date-time-dev libboost-date-time1.74-dev
  libboost-date-time1.74.0 libboost-exception-dev libboost-exception1.74-dev
  libboost-fiber-dev libboost-fiber1.74-dev libboost-fiber1.74.0
  libboost-filesystem-dev libboost-filesystem1.74-dev
  libboost-filesystem1.74.0 libboost-graph-dev libboost-graph-parallel-dev
  libboost-graph-parallel1.74-dev libboost-graph-parallel1.74.0
  libboost-graph1.74-dev libboost-graph1.74.0 libboost-iostreams-dev
  libboost-iostreams1.74-dev libboost-iostreams1.74.0 libboost-locale-dev
  libboost-locale1.74-dev libboost-locale1.74.0 libboost-log-dev
  libboost-log1.74-dev libboost-log1.74.0 libboost-math-dev
  libboost-math1.74-dev libboost-math1.74.0 libboost-mpi-dev
  libboost-mpi-python-dev libboost-mpi-python1.74-dev
  libboost-mpi-python1.74.0 libboost-mpi1.74-dev libboost-mpi1.74.0
  libboost-nowide-dev libboost-nowide1.74-dev libboost-nowide1.74.0
  libboost-numpy-dev libboost-numpy1.74-dev libboost-numpy1.74.0
  libboost-program-options-dev libboost-program-options1.74-dev
  libboost-program-options1.74.0 libboost-python-dev libboost-python1.74-dev
  libboost-python1.74.0 libboost-random-dev libboost-random1.74-dev
  libboost-random1.74.0 libboost-regex-dev libboost-regex1.74-dev
  libboost-regex1.74.0 libboost-serialization-dev
  libboost-serialization1.74-dev libboost-serialization1.74.0
  libboost-stacktrace-dev libboost-stacktrace1.74-dev
  libboost-stacktrace1.74.0 libboost-system-dev libboost-system1.74-dev
  libboost-system1.74.0 libboost-test-dev libboost-test1.74-dev
  libboost-test1.74.0 libboost-thread-dev libboost-thread1.74-dev
  libboost-thread1.74.0 libboost-timer-dev libboost-timer1.74-dev
  libboost-timer1.74.0 libboost-tools-dev libboost-type-erasure-dev
  libboost-type-erasure1.74-dev libboost-type-erasure1.74.0 libboost-wave-dev
  libboost-wave1.74-dev libboost-wave1.74.0 libboost1.74-tools-dev
  libjs-sphinxdoc libjs-underscore python3-dev python3.10-dev
Suggested packages:
  apache2 | lighttpd | httpd libboost1.74-doc gccxml xsltproc doxygen
  docbook-xml docbook-xsl default-jdk fop
The following NEW packages will be installed:
  javascript-common libboost-all-dev libboost-atomic-dev
  libboost-atomic1.74-dev libboost-atomic1.74.0 libboost-chrono-dev
  libboost-chrono1.74-dev libboost-chrono1.74.0 libboost-container-dev
  libboost-container1.74-dev libboost-container1.74.0 libboost-context-dev
  libboost-context1.74-dev libboost-context1.74.0 libboost-coroutine-dev
  libboost-coroutine1.74-dev libboost-coroutine1.74.0 libboost-date-time-dev
  libboost-date-time1.74-dev libboost-date-time1.74.0 libboost-exception-dev
  libboost-exception1.74-dev libboost-fiber-dev libboost-fiber1.74-dev
  libboost-fiber1.74.0 libboost-filesystem-dev libboost-filesystem1.74-dev
  libboost-filesystem1.74.0 libboost-graph-dev libboost-graph-parallel-dev
  libboost-graph-parallel1.74-dev libboost-graph-parallel1.74.0
  libboost-graph1.74-dev libboost-graph1.74.0 libboost-iostreams-dev
  libboost-iostreams1.74-dev libboost-iostreams1.74.0 libboost-locale-dev
  libboost-locale1.74-dev libboost-locale1.74.0 libboost-log-dev
  libboost-log1.74-dev libboost-log1.74.0 libboost-math-dev
  libboost-math1.74-dev libboost-math1.74.0 libboost-mpi-dev
  libboost-mpi-python-dev libboost-mpi-python1.74-dev
  libboost-mpi-python1.74.0 libboost-mpi1.74-dev libboost-mpi1.74.0
  libboost-nowide-dev libboost-nowide1.74-dev libboost-nowide1.74.0
  libboost-numpy-dev libboost-numpy1.74-dev libboost-numpy1.74.0
  libboost-program-options-dev libboost-program-options1.74-dev
  libboost-program-options1.74.0 libboost-python-dev libboost-python1.74-dev
  libboost-python1.74.0 libboost-random-dev libboost-random1.74-dev
  libboost-random1.74.0 libboost-regex-dev libboost-regex1.74-dev
  libboost-regex1.74.0 libboost-serialization-dev
  libboost-serialization1.74-dev libboost-serialization1.74.0
  libboost-stacktrace-dev libboost-stacktrace1.74-dev
  libboost-stacktrace1.74.0 libboost-system-dev libboost-system1.74-dev
  libboost-system1.74.0 libboost-test-dev libboost-test1.74-dev
  libboost-test1.74.0 libboost-thread-dev libboost-thread1.74-dev
  libboost-thread1.74.0 libboost-timer-dev libboost-timer1.74-dev
  libboost-timer1.74.0 libboost-tools-dev libboost-type-erasure-dev
  libboost-type-erasure1.74-dev libboost-type-erasure1.74.0 libboost-wave-dev
  libboost-wave1.74-dev libboost-wave1.74.0 libboost1.74-tools-dev
  libjs-sphinxdoc libjs-underscore python3-dev python3.10-dev
0 upgraded, 100 newly installed, 0 to remove and 59 not upgraded.
Need to get 21.4 MB of archives.
After this operation, 179 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 javascript-common all 11+nmu1 [5,936 B]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost1.74-tools-dev amd64 1.74.0-14ubuntu3 [1,351 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-tools-dev amd64 1.74.0.3ubuntu7 [3,428 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-atomic1.74.0 amd64 1.74.0-14ubuntu3 [224 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-atomic1.74-dev amd64 1.74.0-14ubuntu3 [221 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-atomic-dev amd64 1.74.0.3ubuntu7 [3,544 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-chrono1.74.0 amd64 1.74.0-14ubuntu3 [232 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-chrono1.74-dev amd64 1.74.0-14ubuntu3 [239 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-chrono-dev amd64 1.74.0.3ubuntu7 [3,854 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-container1.74.0 amd64 1.74.0-14ubuntu3 [246 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-container1.74-dev amd64 1.74.0-14ubuntu3 [254 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-container-dev amd64 1.74.0.3ubuntu7 [3,712 B]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-date-time1.74.0 amd64 1.74.0-14ubuntu3 [221 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-serialization1.74.0 amd64 1.74.0-14ubuntu3 [327 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-serialization1.74-dev amd64 1.74.0-14ubuntu3 [375 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-date-time1.74-dev amd64 1.74.0-14ubuntu3 [226 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-system1.74.0 amd64 1.74.0-14ubuntu3 [221 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-system1.74-dev amd64 1.74.0-14ubuntu3 [218 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-thread1.74.0 amd64 1.74.0-14ubuntu3 [262 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-thread1.74-dev amd64 1.74.0-14ubuntu3 [272 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-context1.74.0 amd64 1.74.0-14ubuntu3 [223 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-context1.74-dev amd64 1.74.0-14ubuntu3 [220 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-context-dev amd64 1.74.0.3ubuntu7 [3,456 B]
Get:24 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-coroutine1.74.0 amd64 1.74.0-14ubuntu3 [235 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-coroutine1.74-dev amd64 1.74.0-14ubuntu3 [244 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-coroutine-dev amd64 1.74.0.3ubuntu7 [3,520 B]
Get:27 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-date-time-dev amd64 1.74.0.3ubuntu7 [3,248 B]
Get:28 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-exception1.74-dev amd64 1.74.0-14ubuntu3 [217 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-exception-dev amd64 1.74.0.3ubuntu7 [3,250 B]
Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-filesystem1.74.0 amd64 1.74.0-14ubuntu3 [264 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-filesystem1.74-dev amd64 1.74.0-14ubuntu3 [287 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-fiber1.74.0 amd64 1.74.0-14ubuntu3 [242 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-fiber1.74-dev amd64 1.74.0-14ubuntu3 [254 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-fiber-dev amd64 1.74.0.3ubuntu7 [3,674 B]
Get:35 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-filesystem-dev amd64 1.74.0.3ubuntu7 [3,280 B]
Get:36 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-regex1.74.0 amd64 1.74.0-14ubuntu3 [511 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-graph1.74.0 amd64 1.74.0-14ubuntu3 [304 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-regex1.74-dev amd64 1.74.0-14ubuntu3 [596 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-test1.74.0 amd64 1.74.0-14ubuntu3 [446 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-test1.74-dev amd64 1.74.0-14ubuntu3 [564 kB]
Get:41 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-graph1.74-dev amd64 1.74.0-14ubuntu3 [335 kB]
Get:42 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-graph-dev amd64 1.74.0.3ubuntu7 [3,348 B]
Get:43 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-mpi1.74.0 amd64 1.74.0-14ubuntu3 [259 kB]
Get:44 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-graph-parallel1.74.0 amd64 1.74.0-14ubuntu3 [266 kB]
Get:45 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-graph-parallel1.74-dev amd64 1.74.0-14ubuntu3 [277 kB]
Get:46 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-graph-parallel-dev amd64 1.74.0.3ubuntu7 [3,384 B]
Get:47 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-iostreams1.74.0 amd64 1.74.0-14ubuntu3 [245 kB]
Get:48 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-iostreams1.74-dev amd64 1.74.0-14ubuntu3 [252 kB]
Get:49 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-iostreams-dev amd64 1.74.0.3ubuntu7 [3,238 B]
Get:50 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-locale1.74.0 amd64 1.74.0-14ubuntu3 [413 kB]
Get:51 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-locale1.74-dev amd64 1.74.0-14ubuntu3 [594 kB]
Get:52 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-locale-dev amd64 1.74.0.3ubuntu7 [3,572 B]
Get:53 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-log1.74.0 amd64 1.74.0-14ubuntu3 [592 kB]
Get:54 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-log1.74-dev amd64 1.74.0-14ubuntu3 [853 kB]
Get:55 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-log-dev amd64 1.74.0.3ubuntu7 [3,446 B]
Get:56 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-math1.74.0 amd64 1.74.0-14ubuntu3 [423 kB]
Get:57 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-math1.74-dev amd64 1.74.0-14ubuntu3 [620 kB]
Get:58 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-math-dev amd64 1.74.0.3ubuntu7 [3,454 B]
Get:59 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-mpi1.74-dev amd64 1.74.0-14ubuntu3 [285 kB]
Get:60 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-mpi-dev amd64 1.74.0.3ubuntu7 [3,328 B]
Get:61 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-python1.74.0 amd64 1.74.0-14ubuntu3 [299 kB]
Get:62 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-mpi-python1.74.0 amd64 1.74.0-14ubuntu3 [351 kB]
Get:63 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-mpi-python1.74-dev amd64 1.74.0-14ubuntu3 [225 kB]
Get:64 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-mpi-python-dev amd64 1.74.0.3ubuntu7 [3,382 B]
Get:65 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-numpy1.74.0 amd64 1.74.0-14ubuntu3 [229 kB]
Get:66 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-numpy1.74-dev amd64 1.74.0-14ubuntu3 [233 kB]
Get:67 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-numpy-dev amd64 1.74.0.3ubuntu7 [3,286 B]
Get:68 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-program-options1.74.0 amd64 1.74.0-14ubuntu3 [311 kB]
Get:69 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-program-options1.74-dev amd64 1.74.0-14ubuntu3 [380 kB]
Get:70 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-program-options-dev amd64 1.74.0.3ubuntu7 [3,266 B]
Get:71 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-dev amd64 3.10.12-1~22.04.15 [508 kB]
Get:72 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjs-underscore all 1.13.2~dfsg-2 [118 kB]
Get:73 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjs-sphinxdoc all 4.3.2-1 [139 kB]
Get:74 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-dev amd64 3.10.6-1~22.04.1 [26.0 kB]
Get:75 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-python1.74-dev amd64 1.74.0-14ubuntu3 [323 kB]
Get:76 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-python-dev amd64 1.74.0.3ubuntu7 [3,538 B]
Get:77 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-random1.74.0 amd64 1.74.0-14ubuntu3 [231 kB]
Get:78 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-random1.74-dev amd64 1.74.0-14ubuntu3 [231 kB]
Get:79 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-random-dev amd64 1.74.0.3ubuntu7 [3,258 B]
Get:80 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-regex-dev amd64 1.74.0.3ubuntu7 [3,510 B]
Get:81 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-serialization-dev amd64 1.74.0.3ubuntu7 [3,468 B]
Get:82 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-stacktrace1.74.0 amd64 1.74.0-14ubuntu3 [267 kB]
Get:83 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-stacktrace1.74-dev amd64 1.74.0-14ubuntu3 [232 kB]
Get:84 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-stacktrace-dev amd64 1.74.0.3ubuntu7 [3,260 B]
Get:85 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-system-dev amd64 1.74.0.3ubuntu7 [3,390 B]
Get:86 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-test-dev amd64 1.74.0.3ubuntu7 [3,274 B]
Get:87 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-thread-dev amd64 1.74.0.3ubuntu7 [3,266 B]
Get:88 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-timer1.74.0 amd64 1.74.0-14ubuntu3 [228 kB]
Get:89 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-timer1.74-dev amd64 1.74.0-14ubuntu3 [231 kB]
Get:90 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-timer-dev amd64 1.74.0.3ubuntu7 [3,380 B]
Get:91 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-type-erasure1.74.0 amd64 1.74.0-14ubuntu3 [234 kB]
Get:92 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-type-erasure1.74-dev amd64 1.74.0-14ubuntu3 [239 kB]
Get:93 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-type-erasure-dev amd64 1.74.0.3ubuntu7 [3,344 B]
Get:94 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-wave1.74.0 amd64 1.74.0-14ubuntu3 [449 kB]
Get:95 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-wave1.74-dev amd64 1.74.0-14ubuntu3 [496 kB]
Get:96 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-wave-dev amd64 1.74.0.3ubuntu7 [3,292 B]
Get:97 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-nowide1.74.0 amd64 1.74.0-14ubuntu3 [223 kB]
Get:98 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-nowide1.74-dev amd64 1.74.0-14ubuntu3 [220 kB]
Get:99 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-nowide-dev amd64 1.74.0.3ubuntu7 [3,322 B]
Get:100 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libboost-all-dev amd64 1.74.0.3ubuntu7 [2,268 B]
Fetched 21.4 MB in 3s (6,196 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 100.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package javascript-common.
(Reading database ... 122354 files and directories currently installed.)
Preparing to unpack .../00-javascript-common_11+nmu1_all.deb ...
Unpacking javascript-common (11+nmu1) ...
Selecting previously unselected package libboost1.74-tools-dev.
Preparing to unpack .../01-libboost1.74-tools-dev_1.74.0-14ubuntu3_amd64.deb ...
Unpacking libboost1.74-tools-dev (1.74.0-14ubuntu3) ...
Selecting previously unselected package libboost-tools-dev.
Preparing to unpack .../02-libboost-tools-dev_1.74.0.3ubuntu7_amd64.deb ...
Unpacking libboost-tools-dev (1.74.0.3ubuntu7) ...

### Build and install KenLM from source

In [4]:
!mkdir build
%cd build
!cmake ..
!make -j 4
!sudo make install

mkdir: cannot create directory ‘build’: File exists
/content/kenlm/build
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:101 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.41.0") found components: program_options system thread unit_test_framework
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.8")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/lib/x86_64-linux-gnu/liblzma.so (found version "5.2.5")
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Configuring done (1.3s)
-- Generating done (0.1s)
-- Build files have been written to: /content/kenlm/build
[  1%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/bignum-dtoa.cc.o
[  2%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/bignum.cc.o
[  3%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/cached-powers.cc.o
[  4%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/fast-dtoa.cc.o
[  5%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/fixed-dtoa.cc.o
[  6%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/strtod.cc.o
[  7%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/double-to-string.cc.o
[  8%] Building CXX object util/CMakeFiles/kenlm_util.dir/double-conversion/string-to-double.cc.o
[  9%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/chain.cc.o
[ 10%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/count_records.cc.o
[ 11%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/io.cc.o
[ 12%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/line_input.cc.o
[ 13%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/multi_progress.cc.o
[ 14%] Building CXX object util/CMakeFiles/kenlm_util.dir/stream/rewindable_stream.cc.o
[ 15%] Building CXX object util/CMakeFiles/kenlm_util.dir/bit_packing.cc.o
[ 16%] Building CXX object util/CMakeFiles/kenlm_util.dir/ersatz_progress.cc.o
[ 17%] Building CXX object util/CMakeFiles/kenlm_util.dir/exception.cc.o
[ 18%] Building CXX object util/CMakeFiles/kenlm_util.dir/file.cc.o
[ 19%] Building CXX object util/CMakeFiles/kenlm_util.dir/file_piece.cc.o
[ 20%] Building CXX object util/CMakeFiles/kenlm_util.dir/float_to_string.cc.o
[ 21%] Building CXX object util/CMakeFiles/kenlm_util.dir/integer_to_string.cc.o
[ 22%] Building CXX object util/CMakeFiles/kenlm_util.dir/mmap.cc.o
[ 23%] Building CXX object util/CMakeFiles/kenlm_util.dir/murmur_hash.cc.o
[ 25%] Building CXX object util/CMakeFiles/kenlm_util.dir/parallel_read.cc.o
[ 26%] Building CXX object util/CMakeFiles/kenlm_util.dir/pool.cc.o
[ 27%] Building CXX object util/CMakeFiles/kenlm_util.dir/read_compressed.cc.o
[ 28%] Building CXX object util/CMakeFiles/kenlm_util.dir/scoped.cc.o
[ 29%] Building CXX object util/CMakeFiles/kenlm_util.dir/spaces.cc.o
[ 30%] Building CXX object util/CMakeFiles/kenlm_util.dir/string_piece.cc.o
[ 31%] Building CXX object util/CMakeFiles/kenlm_util.dir/usage.cc.o
[ 32%] Linking CXX static library ../lib/libkenlm_util.a
[ 32%] Built target kenlm_util
[ 33%] Building CXX object util/CMakeFiles/probing_hash_table_benchmark.dir/probing_hash_table_benchmark_main.cc.o
[ 35%] Building CXX object lm/filter/CMakeFiles/kenlm_filter.dir/phrase.cc.o
[ 35%] Building CXX object lm/filter/CMakeFiles/kenlm_filter.dir/arpa_io.cc.o
[ 36%] Building CXX object lm/CMakeFiles/kenlm.dir/bhiksha.cc.o
[ 37%] Building CXX object lm/CMakeFiles/kenlm.dir/binary_format.cc.o
[ 38%] Building CXX object lm/filter/CMakeFiles/kenlm_filter.dir/vocab.cc.o
[ 39%] Building CXX object lm/CMakeFiles/kenlm.dir/config.cc.o
[ 40%] Building CXX object lm/CMakeFiles/kenlm.dir/lm_exception.cc.o
[ 41%] Building CXX object lm/CMakeFiles/kenlm.dir/model.cc.o
[ 42%] Building CXX object lm/CMakeFiles/kenlm.dir/quantize.cc.o
[ 43%] Linking CXX static library ../../lib/libkenlm_filter.a
[ 43%] Built target kenlm_filter
[ 44%] Building CXX object lm/CMakeFiles/kenlm.dir/read_arpa.cc.o
[ 45%] Building CXX object lm/CMakeFiles/kenlm.dir/search_hashed.cc.o
[ 46%] Building CXX object lm/CMakeFiles/kenlm.dir/search_trie.cc.o
[ 47%] Building CXX object lm/CMakeFiles/kenlm.dir/sizes.cc.o
[ 48%] Building CXX object lm/CMakeFiles/kenlm.dir/trie.cc.o
[ 50%] Building CXX object lm/CMakeFiles/kenlm.dir/trie_sort.cc.o
[ 51%] Building CXX object lm/CMakeFiles/kenlm.dir/value_build.cc.o
[ 52%] Building CXX object lm/CMakeFiles/kenlm.dir/virtual_interface.cc.o
[ 53%] Linking CXX executable ../bin/probing_hash_table_benchmark
[ 53%] Built target probing_hash_table_benchmark
[ 54%] Building CXX object lm/CMakeFiles/kenlm.dir/vocab.cc.o
[ 55%] Building CXX object lm/CMakeFiles/kenlm.dir/common/model_buffer.cc.o
[ 56%] Building CXX object lm/CMakeFiles/kenlm.dir/common/print.cc.o
[ 57%] Building CXX object lm/CMakeFiles/kenlm.dir/common/renumber.cc.o
[ 58%] Building CXX object lm/CMakeFiles/kenlm.dir/common/size_option.cc.o
[ 59%] Linking CXX static library ../lib/libkenlm.a
[ 59%] Built target kenlm
[ 60%] Building CXX object lm/CMakeFiles/fragment.dir/fragment_main.cc.o
[ 61%] Building CXX object lm/CMakeFiles/query.dir/query_main.cc.o
[ 62%] Building CXX object lm/CMakeFiles/build_binary.dir/build_binary_main.cc.o
[ 63%] Building CXX object lm/CMakeFiles/kenlm_benchmark.dir/kenlm_benchmark_main.cc.o
[ 64%] Linking CXX executable ../bin/fragment
[ 64%] Built target fragment
[ 65%] Building CXX object lm/builder/CMakeFiles/kenlm_builder.dir/adjust_counts.cc.o
[ 66%] Linking CXX executable ../bin/build_binary
[ 66%] Built target build_binary
[ 67%] Building CXX object lm/filter/CMakeFiles/filter.dir/filter_main.cc.o
[ 68%] Linking CXX executable ../bin/query
[ 68%] Built target query
[ 69%] Building CXX object lm/filter/CMakeFiles/phrase_table_vocab.dir/phrase_table_vocab_main.cc.o
[ 70%] Building CXX object lm/builder/CMakeFiles/kenlm_builder.dir/corpus_count.cc.o
[ 71%] Linking CXX executable ../../bin/phrase_table_vocab
[ 71%] Built target phrase_table_vocab
[ 72%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/backoff_reunification.cc.o
[ 73%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/bounded_sequence_encoding.cc.o
[ 75%] Building CXX object lm/builder/CMakeFiles/kenlm_builder.dir/initial_probabilities.cc.o
[ 76%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/merge_probabilities.cc.o
[ 77%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/merge_vocab.cc.o
[ 78%] Building CXX object lm/builder/CMakeFiles/kenlm_builder.dir/interpolate.cc.o
[ 79%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/normalize.cc.o
[ 80%] Building CXX object lm/builder/CMakeFiles/kenlm_builder.dir/output.cc.o
[ 81%] Linking CXX executable ../bin/kenlm_benchmark
[ 81%] Built target kenlm_benchmark
[ 82%] Building CXX object lm/builder/CMakeFiles/kenlm_builder.dir/pipeline.cc.o
[ 83%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/pipeline.cc.o
[ 84%] Linking CXX executable ../../bin/filter
[ 84%] Built target filter
[ 85%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/split_worker.cc.o
[ 86%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/tune_derivatives.cc.o
[ 87%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/tune_instances.cc.o
[ 88%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/tune_weights.cc.o
[ 89%] Building CXX object lm/interpolate/CMakeFiles/kenlm_interpolate.dir/universal_vocab.cc.o
[ 90%] Linking CXX static library ../../lib/libkenlm_builder.a
[ 90%] Built target kenlm_builder
[ 91%] Building CXX object lm/builder/CMakeFiles/lmplz.dir/lmplz_main.cc.o
[ 92%] Building CXX object lm/builder/CMakeFiles/count_ngrams.dir/count_ngrams_main.cc.o
[ 93%] Linking CXX executable ../../bin/lmplz
[ 93%] Built target lmplz
[ 94%] Linking CXX static library ../../lib/libkenlm_interpolate.a
[ 94%] Built target kenlm_interpolate
[ 95%] Building CXX object lm/interpolate/CMakeFiles/interpolate.dir/interpolate_main.cc.o
[ 96%] Building CXX object lm/interpolate/CMakeFiles/streaming_example.dir/streaming_example_main.cc.o
[ 97%] Linking CXX executable ../../bin/count_ngrams
[ 97%] Built target count_ngrams
[ 98%] Linking CXX executable ../../bin/interpolate
[ 98%] Built target interpolate
[100%] Linking CXX executable ../../bin/streaming_example
[100%] Built target streaming_example
[ 32%] Built target kenlm_util
[ 34%] Built target probing_hash_table_benchmark
[ 55%] Built target kenlm
[ 57%] Built target query
[ 59%] Built target fragment
[ 61%] Built target build_binary
[ 63%] Built target kenlm_benchmark
[ 70%] Built target kenlm_builder
[ 72%] Built target lmplz
[ 75%] Built target count_ngrams
[ 79%] Built target kenlm_filter
[ 81%] Built target filter
[ 83%] Built target phrase_table_vocab
[ 95%] Built target kenlm_interpolate
[ 97%] Built target interpolate
[100%] Built target streaming_example
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/share/kenlm/cmake/kenlmTargets.cmake
-- Installing: /usr/local/share/kenlm/cmake/kenlmTargets-release.cmake
-- Installing: /usr/local/include/kenlm/util/bit_packing.hh
-- Installing: /usr/local/include/kenlm/util/ersatz_progress.hh
-- Installing: /usr/local/include/kenlm/util/exception.hh
-- Installing: /usr/local/include/kenlm/util/fake_ostream.hh
-- Installing: /usr/local/include/kenlm/util/file.hh
-- Installing: /usr/local/include/kenlm/util/file_piece.hh
-- Installing: /usr/local/include/kenlm/util/file_stream.hh
-- Installing: /usr/local/include/kenlm/util/fixed_array.hh
-- Installing: /usr/local/include/kenlm/util/float_to_string.hh
-- Installing: /usr/local/include/kenlm/util/getopt.hh
-- Installing: /usr/local/include/kenlm/util/have.hh
-- Installing: /usr/local/include/kenlm/util/integer_to_string.hh
-- Installing: /usr/local/include/kenlm/util/joint_sort.hh
-- Installing: /usr/local/include/kenlm/util/mmap.hh
-- Installing: /usr/local/include/kenlm/util/multi_intersection.hh
-- Installing: /usr/local/include/kenlm/util/murmur_hash.hh
-- Installing: /usr/local/include/kenlm/util/parallel_read.hh
-- Installing: /usr/local/include/kenlm/util/pcqueue.hh
-- Installing: /usr/local/include/kenlm/util/pool.hh
-- Installing: /usr/local/include/kenlm/util/probing_hash_table.hh
-- Installing: /usr/local/include/kenlm/util/proxy_iterator.hh
-- Installing: /usr/local/include/kenlm/util/read_compressed.hh
-- Installing: /usr/local/include/kenlm/util/scoped.hh
-- Installing: /usr/local/include/kenlm/util/sized_iterator.hh
-- Installing: /usr/local/include/kenlm/util/sorted_uniform.hh
-- Installing: /usr/local/include/kenlm/util/spaces.hh
-- Installing: /usr/local/include/kenlm/util/string_piece.hh
-- Installing: /usr/local/include/kenlm/util/string_piece_hash.hh
-- Installing: /usr/local/include/kenlm/util/string_stream.hh
-- Installing: /usr/local/include/kenlm/util/thread_pool.hh
-- Installing: /usr/local/include/kenlm/util/tokenize_piece.hh
-- Installing: /usr/local/include/kenlm/util/usage.hh
-- Installing: /usr/local/include/kenlm/util/double-conversion/bignum-dtoa.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/bignum.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/cached-powers.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/diy-fp.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/double-conversion.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/double-to-string.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/fast-dtoa.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/fixed-dtoa.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/ieee.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/string-to-double.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/strtod.h
-- Installing: /usr/local/include/kenlm/util/double-conversion/utils.h
-- Installing: /usr/local/include/kenlm/util/stream/block.hh
-- Installing: /usr/local/include/kenlm/util/stream/chain.hh
-- Installing: /usr/local/include/kenlm/util/stream/config.hh
-- Installing: /usr/local/include/kenlm/util/stream/count_records.hh
-- Installing: /usr/local/include/kenlm/util/stream/io.hh
-- Installing: /usr/local/include/kenlm/util/stream/line_input.hh
-- Installing: /usr/local/include/kenlm/util/stream/multi_progress.hh
-- Installing: /usr/local/include/kenlm/util/stream/multi_stream.hh
-- Installing: /usr/local/include/kenlm/util/stream/rewindable_stream.hh
-- Installing: /usr/local/include/kenlm/util/stream/sort.hh
-- Installing: /usr/local/include/kenlm/util/stream/stream.hh
-- Installing: /usr/local/include/kenlm/util/stream/typed_stream.hh
-- Installing: /usr/local/include/kenlm/lm/bhiksha.hh
-- Installing: /usr/local/include/kenlm/lm/binary_format.hh
-- Installing: /usr/local/include/kenlm/lm/blank.hh
-- Installing: /usr/local/include/kenlm/lm/config.hh
-- Installing: /usr/local/include/kenlm/lm/enumerate_vocab.hh
-- Installing: /usr/local/include/kenlm/lm/facade.hh
-- Installing: /usr/local/include/kenlm/lm/left.hh
-- Installing: /usr/local/include/kenlm/lm/lm_exception.hh
-- Installing: /usr/local/include/kenlm/lm/max_order.hh
-- Installing: /usr/local/include/kenlm/lm/model.hh
-- Installing: /usr/local/include/kenlm/lm/model_type.hh
-- Installing: /usr/local/include/kenlm/lm/ngram_query.hh
-- Installing: /usr/local/include/kenlm/lm/partial.hh
-- Installing: /usr/local/include/kenlm/lm/quantize.hh
-- Installing: /usr/local/include/kenlm/lm/read_arpa.hh
-- Installing: /usr/local/include/kenlm/lm/return.hh
-- Installing: /usr/local/include/kenlm/lm/search_hashed.hh
-- Installing: /usr/local/include/kenlm/lm/search_trie.hh
-- Installing: /usr/local/include/kenlm/lm/sizes.hh
-- Installing: /usr/local/include/kenlm/lm/state.hh
-- Installing: /usr/local/include/kenlm/lm/trie.hh
-- Installing: /usr/local/include/kenlm/lm/trie_sort.hh
-- Installing: /usr/local/include/kenlm/lm/value.hh
-- Installing: /usr/local/include/kenlm/lm/value_build.hh
-- Installing: /usr/local/include/kenlm/lm/virtual_interface.hh
-- Installing: /usr/local/include/kenlm/lm/vocab.hh
-- Installing: /usr/local/include/kenlm/lm/weights.hh
-- Installing: /usr/local/include/kenlm/lm/word_index.hh
-- Installing: /usr/local/include/kenlm/lm/builder/adjust_counts.hh
-- Installing: /usr/local/include/kenlm/lm/builder/combine_counts.hh
-- Installing: /usr/local/include/kenlm/lm/builder/corpus_count.hh
-- Installing: /usr/local/include/kenlm/lm/builder/debug_print.hh
-- Installing: /usr/local/include/kenlm/lm/builder/discount.hh
-- Installing: /usr/local/include/kenlm/lm/builder/hash_gamma.hh
-- Installing: /usr/local/include/kenlm/lm/builder/header_info.hh
-- Installing: /usr/local/include/kenlm/lm/builder/initial_probabilities.hh
-- Installing: /usr/local/include/kenlm/lm/builder/interpolate.hh
-- Installing: /usr/local/include/kenlm/lm/builder/output.hh
-- Installing: /usr/local/include/kenlm/lm/builder/payload.hh
-- Installing: /usr/local/include/kenlm/lm/builder/pipeline.hh
-- Installing: /usr/local/include/kenlm/lm/common/compare.hh
-- Installing: /usr/local/include/kenlm/lm/common/joint_order.hh
-- Installing: /usr/local/include/kenlm/lm/common/model_buffer.hh
-- Installing: /usr/local/include/kenlm/lm/common/ngram.hh
-- Installing: /usr/local/include/kenlm/lm/common/ngram_stream.hh
-- Installing: /usr/local/include/kenlm/lm/common/print.hh
-- Installing: /usr/local/include/kenlm/lm/common/renumber.hh
-- Installing: /usr/local/include/kenlm/lm/common/size_option.hh
-- Installing: /usr/local/include/kenlm/lm/common/special.hh
-- Installing: /usr/local/include/kenlm/lm/filter/arpa_io.hh
-- Installing: /usr/local/include/kenlm/lm/filter/count_io.hh
-- Installing: /usr/local/include/kenlm/lm/filter/format.hh
-- Installing: /usr/local/include/kenlm/lm/filter/phrase.hh
-- Installing: /usr/local/include/kenlm/lm/filter/thread.hh
-- Installing: /usr/local/include/kenlm/lm/filter/vocab.hh
-- Installing: /usr/local/include/kenlm/lm/filter/wrapper.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/backoff_matrix.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/backoff_reunification.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/bounded_sequence_encoding.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/interpolate_info.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/merge_probabilities.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/merge_vocab.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/normalize.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/pipeline.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/split_worker.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/tune_derivatives.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/tune_instances.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/tune_matrix.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/tune_weights.hh
-- Installing: /usr/local/include/kenlm/lm/interpolate/universal_vocab.hh
-- Installing: /usr/local/share/kenlm/cmake/kenlmConfig.cmake
-- Installing: /usr/local/lib/libkenlm_util.a
-- Installing: /usr/local/bin/probing_hash_table_benchmark
-- Installing: /usr/local/lib/libkenlm.a
-- Installing: /usr/local/bin/query
-- Installing: /usr/local/bin/fragment
-- Installing: /usr/local/bin/build_binary
-- Installing: /usr/local/bin/kenlm_benchmark
-- Installing: /usr/local/bin/lmplz
-- Installing: /usr/local/bin/count_ngrams
-- Installing: /usr/local/lib/libkenlm_builder.a
-- Installing: /usr/local/bin/filter
-- Installing: /usr/local/bin/phrase_table_vocab
-- Installing: /usr/local/lib/libkenlm_filter.a
-- Installing: /usr/local/bin/interpolate
-- Installing: /usr/local/bin/streaming_example
-- Installing: /usr/local/lib/libkenlm_interpolate.a

### Add KenLM binaries to the system PATH and verify installation

In [5]:
import os
os.environ['PATH'] += ":/content/kenlm/build/bin"  # Use your exact path
!echo $PATH  # Verify
!which lmplz  # Test

/opt/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin:/content/kenlm/build/bin
/usr/local/bin/lmplz

### Initialize the CTC tokenizer, SeamlessM4T feature extractor, and Wav2Vec2-BERT processor

In [6]:
import re
import json
import unicodedata
import numpy as np
import torch
from dataclasses import dataclass
from typing import Dict, List, Union

from datasets import load_dataset, Audio, concatenate_datasets
import evaluate

from transformers import (
    Wav2Vec2CTCTokenizer,
    SeamlessM4TFeatureExtractor,
    Wav2Vec2BertProcessor,
    Wav2Vec2BertForCTC,
    TrainingArguments,
    Trainer,
)

### Load the Dhivehi Common Voice dataset and remove unused metadata columns

In [7]:
dv_train = load_dataset("fsicoli/common_voice_22_0", "dv", split="train+validation", trust_remote_code=True)
dv_test  = load_dataset("fsicoli/common_voice_22_0", "dv", split="test", trust_remote_code=True)

dv_train = dv_train.remove_columns(["accent","age","client_id","down_votes","gender","locale","segment","up_votes"])
dv_test  = dv_test.remove_columns(["accent","age","client_id","down_votes","gender","locale","segment","up_votes"])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

common_voice_22_0.py: 0.00B [00:00, ?B/s]

languages.py: 0.00B [00:00, ?B/s]

release_stats.py: 0.00B [00:00, ?B/s]

Downloading data: 0.00B [00:00, ?B/s]

audio/dv/train/dv_train_0.tar:   0%|          | 0.00/98.9M [00:00<?, ?B/s]

audio/dv/dev/dv_dev_0.tar:   0%|          | 0.00/87.6M [00:00<?, ?B/s]

audio/dv/test/dv_test_0.tar:   0%|          | 0.00/89.8M [00:00<?, ?B/s]

audio/dv/other/dv_other_0.tar:   0%|          | 0.00/452M [00:00<?, ?B/s]

audio/dv/invalidated/dv_invalidated_0.ta(…):   0%|          | 0.00/64.3M [00:00<?, ?B/s]

train.tsv: 0.00B [00:00, ?B/s]

dev.tsv: 0.00B [00:00, ?B/s]

test.tsv: 0.00B [00:00, ?B/s]

other.tsv: 0.00B [00:00, ?B/s]

invalidated.tsv: 0.00B [00:00, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Reading metadata...: 2654it [00:00, 121041.28it/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Reading metadata...: 2243it [00:00, 119259.98it/s]

Generating test split: 0 examples [00:00, ? examples/s]

Reading metadata...: 2222it [00:00, 118840.93it/s]

Generating other split: 0 examples [00:00, ? examples/s]

Reading metadata...: 0it [00:00, ?it/s]
Reading metadata...: 15104it [00:00, 128509.93it/s]

Generating invalidated split: 0 examples [00:00, ? examples/s]

Reading metadata...: 1652it [00:00, 108734.39it/s]

### Install the wget package for downloading files

In [8]:
!pip install wget

Collecting wget
  Downloading wget-3.2.zip (10 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: wget
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9655 sha256=10c66a459dced0fee27542c54b556c1056067a52d049b7b71890620ccead4a3a
  Stored in directory: /root/.cache/pip/wheels/01/46/3b/e29ffbe4ebe614ff224bad40fc6a5773a67a163251585a13a9
Successfully built wget
Installing collected packages: wget
Successfully installed wget-3.2

### Load the Sinhala ASR dataset with specified train/test splits

In [38]:
import os
import aiohttp
from datasets import load_dataset

os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "180"
os.environ["HF_HUB_ETAG_TIMEOUT"] = "180"

splits = load_dataset(
    "keshan/large-sinhala-asr-dataset",
    "si",
    split={
        "train": "train[:20%]",
        "test": "test[:20%]",
    },
    trust_remote_code=True,
    storage_options={
        "client_kwargs": {
            "timeout": aiohttp.ClientTimeout(total=3600)
        }
    },
)

si_train = splits["train"].rename_column("file", "audio").remove_columns(["filename", "x"])
si_test  = splits["test"].rename_column("file", "audio").remove_columns(["filename", "x"])


print("Sinhala train size:", len(si_train))
print("Sinhala test size:", len(si_test))

Sinhala train size: 26509
Sinhala test size: 4678

### Define and apply text cleaning: remove punctuation, special characters, and filter out Arabic script rows

In [10]:
 # -------- Dhivehi cleaning --------
chars_to_remove_regex_dv = r'[\,\?\.\!\-\;\:\"\“\%\‘\”\�\'\»\«]'
arabic_pattern = re.compile(r"[\u0600-\u06FF]")

def dv_clean(batch):
    s = re.sub(chars_to_remove_regex_dv, "", batch["sentence"]).lower()
    # remove Arabic rows
    if arabic_pattern.search(s):
        batch["sentence"] = ""
        return batch
    # remove latin
    s = re.sub(r"[a-z]+", "", s)
    batch["sentence"] = s.strip()
    return batch

# -------- Sinhala cleaning --------
chars_to_remove_regex_si = r'[\,\?\.\!\-\;\:\"\“\%\‘\”\�\(\)\'\”\‘‘\’\ʻ\”\“\–\—\…\»\«।॥]'
sinhala_allowed = re.compile(r"^[\u0D80-\u0DFF\s]+$")

def si_clean(batch):
    s = unicodedata.normalize("NFC", batch["sentence"])
    s = re.sub(chars_to_remove_regex_si, "", s)
    s = re.sub(r"[A-Za-z0-9]", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    batch["sentence"] = s
    return batch

### Apply cleaning functions and filter out empty sentences from both Dhivehi and Sinhala datasets

In [11]:
dv_train = dv_train.map(dv_clean).filter(lambda x: len(x["sentence"]) > 0)
dv_test  = dv_test.map(dv_clean).filter(lambda x: len(x["sentence"]) > 0)

si_train = si_train.map(si_clean).filter(lambda x: bool(sinhala_allowed.match(x["sentence"])) if x["sentence"] else False)
si_test  = si_test.map(si_clean).filter(lambda x: bool(sinhala_allowed.match(x["sentence"])) if x["sentence"] else False)

Map:   0%|          | 0/4897 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4897 [00:00<?, ? examples/s]

Map:   0%|          | 0/2222 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2222 [00:00<?, ? examples/s]

Map:   0%|          | 0/26509 [00:00<?, ? examples/s]

Filter:   0%|          | 0/26509 [00:00<?, ? examples/s]

Map:   0%|          | 0/4678 [00:00<?, ? examples/s]

Filter:   0%|          | 0/4678 [00:00<?, ? examples/s]

### Resample all audio to 16kHz for both Dhivehi and Sinhala datasets

In [12]:
dv_train = dv_train.cast_column("audio", Audio(sampling_rate=16_000))
dv_test  = dv_test.cast_column("audio", Audio(sampling_rate=16_000))
si_train = si_train.cast_column("audio", Audio(sampling_rate=16_000))
si_test  = si_test.cast_column("audio", Audio(sampling_rate=16_000))

### Extract the combined character vocabulary from both Dhivehi and Sinhala datasets

In [13]:
def extract_all_chars(batch):
    all_text = " ".join(batch["sentence"])
    vocab = list(set(all_text))
    return {"vocab": [vocab], "all_text": [all_text]}

all_train_text = concatenate_datasets([
    dv_train.select_columns(["sentence"]),
    si_train.select_columns(["sentence"]),
])
all_test_text = concatenate_datasets([
    dv_test.select_columns(["sentence"]),
    si_test.select_columns(["sentence"]),
])

vocab_train = all_train_text.map(
    extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True,
    remove_columns=all_train_text.column_names
)
vocab_test = all_test_text.map(
    extract_all_chars, batched=True, batch_size=-1, keep_in_memory=True,
    remove_columns=all_test_text.column_names
)

vocab_list = list(set(vocab_train["vocab"][0]) | set(vocab_test["vocab"][0]))
vocab_dict = {v: k for k, v in enumerate(sorted(vocab_list))}

# Space -> word delimiter |
vocab_dict["|"] = vocab_dict[" "]
del vocab_dict[" "]


# Specials
vocab_dict["[UNK]"] = len(vocab_dict)
vocab_dict["[PAD]"] = len(vocab_dict)

with open("vocab.json", "w", encoding="utf-8") as vocab_file:
    json.dump(vocab_dict, vocab_file, ensure_ascii=False)

print("Vocab size:", len(vocab_dict))

Map:   0%|          | 0/26067 [00:00<?, ? examples/s]

Map:   0%|          | 0/5938 [00:00<?, ? examples/s]

Vocab size: 130

### Initialize the CTC tokenizer, SeamlessM4T feature extractor, and Wav2Vec2-BERT processor

In [14]:
tokenizer = Wav2Vec2CTCTokenizer.from_pretrained(
    "./",
    unk_token="[UNK]",
    pad_token="[PAD]",
    word_delimiter_token="|",
)

feature_extractor = SeamlessM4TFeatureExtractor(
    feature_size=80,
    num_mel_bins=80,
    sampling_rate=16000,
    padding_value=0.0,
)

processor = Wav2Vec2BertProcessor(feature_extractor=feature_extractor, tokenizer=tokenizer)

### Write all transcriptions to a text file for KenLM language model training

In [15]:
with open("lm_corpus.txt", "w", encoding="utf-8") as f:
    for ex in all_train_text:
        s = ex["sentence"].strip()
        if s:
            f.write(s + "\n")
    for ex in all_test_text:
        s = ex["sentence"].strip()
        if s:
            f.write(s + "\n")

print("Wrote LM corpus to lm_corpus.txt")

Wrote LM corpus to lm_corpus.txt

### Define the dataset preparation function: extract audio features and encode text labels, then apply to train and test sets

In [16]:
def prepare_dataset(batch):
    audio = batch["audio"]
    batch["input_features"] = processor(audio["array"], sampling_rate=audio["sampling_rate"]).input_features[0]
    batch["input_length"] = len(batch["input_features"])
    batch["labels"] = processor(text=batch["sentence"]).input_ids
    return batch

dv_train_p = dv_train.map(prepare_dataset, remove_columns=dv_train.column_names)
dv_test_p  = dv_test.map(prepare_dataset,  remove_columns=dv_test.column_names)
si_train_p = si_train.map(prepare_dataset, remove_columns=si_train.column_names)
si_test_p  = si_test.map(prepare_dataset,  remove_columns=si_test.column_names)

Map:   0%|          | 0/4639 [00:00<?, ? examples/s]

Map:   0%|          | 0/2107 [00:00<?, ? examples/s]

Map:   0%|          | 0/21428 [00:00<?, ? examples/s]

Map:   0%|          | 0/3831 [00:00<?, ? examples/s]

### Concatenate Dhivehi and Sinhala processed datasets into unified train and test sets

In [17]:
train = concatenate_datasets([dv_train_p, si_train_p]).shuffle(seed=42)
test  = concatenate_datasets([dv_test_p,  si_test_p]).shuffle(seed=42)

print("Train size:", len(train))
print("Test size:", len(test))

Train size: 26067
Test size: 5938

### Define a custom data collator that pads input features and labels for CTC training

In [18]:
@dataclass
class DataCollatorCTCWithPadding:
    processor: Wav2Vec2BertProcessor
    padding: Union[bool, str] = True

    def __call__(self, features: List[Dict]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_features": f["input_features"]} for f in features]
        label_features = [{"input_ids": f["labels"]} for f in features]

        batch = self.processor.pad(input_features, padding=self.padding, return_tensors="pt")
        labels_batch = self.processor.pad(labels=label_features, padding=self.padding, return_tensors="pt")

        labels = labels_batch["input_ids"].masked_fill(labels_batch["attention_mask"].ne(1), -100)
        batch["labels"] = labels
        return batch

data_collator = DataCollatorCTCWithPadding(processor=processor, padding=True)

### Train a trigram KenLM language model from the corpus

In [19]:
!lmplz -o 3 < lm_corpus.txt > lm.arpa

=== 1/5 Counting and sorting n-grams ===
Reading /content/kenlm/build/lm_corpus.txt
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Unigram tokens 153082 types 41491
=== 2/5 Calculating and sorting adjusted counts ===
Chain sizes: 1:497892 2:24940126208 3:46762737664
Statistics:
1 41491 D1=0.724133 D2=1.11098 D3+=1.32224
2 120888 D1=0.890628 D2=1.15597 D3+=1.39493
3 134489 D1=0.847419 D2=1.64897 D3+=2.16776
Memory estimate for binary LM:
type      kB
probing 6250 assuming -p 1.5
probing 7121 assuming -r models -p 1.5
trie    3175 without quantization
trie    2107 assuming -q 8 -b 8 quantization
trie    3014 assuming -a 22 array pointer compression
trie    1946 assuming -a 22 -q 8 -b 8 array pointer compression and quantization
=== 3/5 Calculating and sorting initial probabilities ===
Chain sizes: 1:497892 2:1934208 3:2689780
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
####################################################################################################
=== 4/5 Calculating and writing order-interpolated probabilities ===
Chain sizes: 1:497892 2:1934208 3:2689780
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
####################################################################################################
=== 5/5 Writing ARPA model ===
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Name:lmplz	VmPeak:70179072 kB	VmRSS:11708 kB	RSSMax:16185980 kB	user:1.28118	sys:6.90461	CPU:8.18583	real:8.14129

### Install pyctcdecode library for CTC beam search decoding with language model support

In [20]:
!pip install pyctcdecode

Collecting pyctcdecode
  Downloading pyctcdecode-0.5.0-py2.py3-none-any.whl.metadata (20 kB)
Collecting numpy<2.0.0,>=1.15.0 (from pyctcdecode)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.5 MB/s eta 0:00:00
Collecting pygtrie<3.0,>=2.1 (from pyctcdecode)
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Collecting hypothesis<7,>=6.14 (from pyctcdecode)
  Downloading hypothesis-6.151.10-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sortedcontainers<3.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from hypothesis<7,>=6.14->pyctcdecode) (2.4.0)
Downloading pyctcdecode-0.5.0-py2.py3-none-any.whl (39 kB)
Downloading hypothesis-6.151.10-py3-none-any.whl (529 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.5/529.5 kB 17.2 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 130.3 MB/s eta 0:00:00
Downloading pygtrie-2.5.0-py3-none-any.whl (25 kB)
Installing collected packages: pygtrie, numpy, hypothesis, pyctcdecode
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
Successfully installed hypothesis-6.151.10 numpy-1.26.4 pyctcdecode-0.5.0 pygtrie-2.5.0

### Build a CTC beam search decoder with KenLM language model integration

In [21]:
from pyctcdecode import build_ctcdecoder

# get labels in ID order
vocab = processor.tokenizer.get_vocab()  # token -> id
id2token = {v: k for k, v in vocab.items()}
labels = [id2token[i] for i in range(len(id2token))]

# path to your trained KenLM model (arpa or binary)
kenlm_model_path = "lm.arpa"  # <-- change if you use another path/name

decoder = build_ctcdecoder(
    labels=labels,
    kenlm_model_path=kenlm_model_path,
    alpha=0.5,  # tune on dev
    beta=1.0  # tune on dev
)

WARNING:pyctcdecode.alphabet:Found entries of length > 1 in alphabet. This is unusual unless style is BPE, but the alphabet was not recognized as BPE type. Is this correct?

### Define the evaluation metrics function using LM-aided beam search decoding to compute WER and CER

In [22]:
import evaluate
import torch

wer_metric = evaluate.load("wer")
cer_metric = evaluate.load("cer")

def compute_metrics(pred):
    pred_logits = pred.predictions
    label_ids = pred.label_ids

    # Convert logits to probabilities
    probs = torch.softmax(torch.tensor(pred_logits), dim=-1).numpy()

    # Decode with LM
    pred_str = [decoder.decode(p, beam_width=64) for p in probs]

    # Replace -100 with pad_token_id
    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id
    label_str = processor.batch_decode(label_ids, group_tokens=False)

    wer = wer_metric.compute(predictions=pred_str, references=label_str)
    cer = cer_metric.compute(predictions=pred_str, references=label_str)

    return {"wer": wer, "cer": cer}

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

### Load the pre-trained W2V-BERT 2.0 model with an adapter and CTC head for fine-tuning

In [23]:
model = Wav2Vec2BertForCTC.from_pretrained(
    "facebook/w2v-bert-2.0",
    add_adapter=True,
    pad_token_id=processor.tokenizer.pad_token_id,
    vocab_size=len(processor.tokenizer),
)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.32G [00:00<?, ?B/s]

Some weights of Wav2Vec2BertForCTC were not initialized from the model checkpoint at facebook/w2v-bert-2.0 and are newly initialized: ['lm_head.bias', 'lm_head.weight', 'wav2vec2_bert.adapter.layers.0.ffn.intermediate_dense.bias', 'wav2vec2_bert.adapter.layers.0.ffn.intermediate_dense.weight', 'wav2vec2_bert.adapter.layers.0.ffn.output_dense.bias', 'wav2vec2_bert.adapter.layers.0.ffn.output_dense.weight', 'wav2vec2_bert.adapter.layers.0.ffn_layer_norm.bias', 'wav2vec2_bert.adapter.layers.0.ffn_layer_norm.weight', 'wav2vec2_bert.adapter.layers.0.residual_conv.bias', 'wav2vec2_bert.adapter.layers.0.residual_conv.weight', 'wav2vec2_bert.adapter.layers.0.residual_layer_norm.bias', 'wav2vec2_bert.adapter.layers.0.residual_layer_norm.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_k.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_k.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_out.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_out.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_q.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_q.weight', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_v.bias', 'wav2vec2_bert.adapter.layers.0.self_attn.linear_v.weight', 'wav2vec2_bert.adapter.layers.0.self_attn_conv.bias', 'wav2vec2_bert.adapter.layers.0.self_attn_conv.weight', 'wav2vec2_bert.adapter.layers.0.self_attn_layer_norm.bias', 'wav2vec2_bert.adapter.layers.0.self_attn_layer_norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

### Configure training hyperparameters: batch size, learning rate, evaluation strategy, checkpointing, and early stopping

In [24]:
from transformers import TrainingArguments, Trainer, Wav2Vec2BertForCTC, EarlyStoppingCallback

training_args = TrainingArguments(
    output_dir="./outputs",
    group_by_length=True,
    per_device_train_batch_size=16,
    gradient_accumulation_steps=2,
    num_train_epochs=10,
    gradient_checkpointing=True,
    fp16=True,

    eval_strategy="steps",     # FIXED
    eval_steps=300,

    logging_strategy="steps",
    logging_steps=300,

    save_strategy="steps",
    save_steps=2700,

    learning_rate=5e-5,
    warmup_steps=500,
    save_total_limit=2,

    load_best_model_at_end=True,
    metric_for_best_model="eval_wer",   # FIXED
    greater_is_better=False,

    push_to_hub=False,
    report_to="none",
)

trainer = Trainer(
    model=model,
    data_collator=data_collator,
    args=training_args,
    compute_metrics=compute_metrics,
    train_dataset=train,
    eval_dataset=test,
    tokenizer=processor
)

/tmp/ipykernel_664/1422347001.py:33: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

### Start the fine-tuning training run

In [25]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 131, 'bos_token_id': 130}.

TrainOutput(global_step=8150, training_loss=417.23020417944787, metrics={'train_runtime': 17729.7613, 'train_samples_per_second': 14.702, 'train_steps_per_second': 0.46, 'total_flos': 3.4309094886272336e+19, 'train_loss': 417.23020417944787, 'epoch': 10.0})

### Mount Google Drive for persistent storage

In [27]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Copy the best checkpoint to Google Drive for persistent storage

In [28]:
!cp -r ./outputs/checkpoint-8150 /content/drive/MyDrive/final_model90

### Run greedy CTC inference on the test set and compute WER/CER

In [30]:
from transformers import AutoModelForCTC, Wav2Vec2BertProcessor
import torch
import numpy as np

all_pred = []
all_refs = []

checkpoint_dir = "/content/kenlm/build/outputs/checkpoint-8150"

model = AutoModelForCTC.from_pretrained(checkpoint_dir).to("cuda")
processor = Wav2Vec2BertProcessor.from_pretrained(checkpoint_dir)

model.eval()

for ex in dv_test_p:
    input_feats = torch.tensor(ex["input_features"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        logits = model(input_feats).logits

    # Convert logits to probabilities for LM decoding
    probs = torch.softmax(logits[0], dim=-1).cpu().numpy()

    # Decode with language model
    pred_text = decoder.decode(probs)

    # Reference text
    ref_text = processor.decode(ex["labels"], group_tokens=False)

    all_pred.append(pred_text)
    all_refs.append(ref_text)

wer = wer_metric.compute(predictions=all_pred, references=all_refs)
cer = cer_metric.compute(predictions=all_pred, references=all_refs)

print(f"WER (Dhivehi only, LM decode): {wer:.4f}")
print(f"CER (Dhivehi only, LM decode): {cer:.4f}")

for idx in range(min(3, len(all_refs))):
    print("\n--- Example", idx, "---")
    print("REF :", all_refs[idx])
    print("PRED:", all_pred[idx])

WER (Dhivehi only, LM decode): 0.1334
CER (Dhivehi only, LM decode): 0.0304

--- Example 0 ---
REF : ޕިކަޕް މަރާމާތުކޮށްދޭނެ ފަރާތެއް ހޯދުން
PRED: ޕިކަޕް މަރާމާތުކޮށްދޭނެ ފަރާތެއް ހޯދުން

--- Example 1 ---
REF : އަންޖޫދާ މަޑުމަޑުން އެހެން ބުނެލުމުން ރިޝްކާ ވެސް އިތުރު ސުވާލެއް ނުކުރޭ
PRED: އަންޖޫދާ މަޑުމަޑުން އެހެން ބުނެލުމުން ރިޝްކާ ވެސް އިތުރު ސުވާލެއް ނުކުރޭ

--- Example 2 ---
REF : އެސްފިޔަތަކުން ވަނީ ނިދި ގެއްލިފަ
PRED: އެސްފިޔަތަކުން ވަނީ ނިދި ގެއްލިފަ

### Run greedy CTC inference on the test set and compute WER/CER

In [31]:
from transformers import AutoModelForCTC, Wav2Vec2BertProcessor
import torch
import numpy as np

all_pred = []
all_refs = []

checkpoint_dir = "/content/kenlm/build/outputs/checkpoint-8150"

model = AutoModelForCTC.from_pretrained(checkpoint_dir).to("cuda")
processor = Wav2Vec2BertProcessor.from_pretrained(checkpoint_dir)

model.eval()

for ex in si_test_p:
    input_feats = torch.tensor(ex["input_features"]).unsqueeze(0).to(model.device)

    with torch.no_grad():
        logits = model(input_feats).logits

    # Convert logits to probabilities for LM decoding
    probs = torch.softmax(logits[0], dim=-1).cpu().numpy()

    # Decode with language model
    pred_text = decoder.decode(probs)

    # Reference text
    ref_text = processor.decode(ex["labels"], group_tokens=False)

    all_pred.append(pred_text)
    all_refs.append(ref_text)

wer = wer_metric.compute(predictions=all_pred, references=all_refs)
cer = cer_metric.compute(predictions=all_pred, references=all_refs)

print(f"WER (Sinhala only, LM decode): {wer:.4f}")
print(f"CER (Sinhala only, LM decode): {cer:.4f}")

for idx in range(min(3, len(all_refs))):
    print("\n--- Example", idx, "---")
    print("REF :", all_refs[idx])
    print("PRED:", all_pred[idx])

WER (Sinhala only, LM decode): 0.0835
CER (Sinhala only, LM decode): 0.0226

--- Example 0 ---
REF : ආචාර්යවරිය නම් ලකුණු කරන අතරතුර
PRED: ආචාර්යවරිය නම් ලකුණු කරන අතරතුර

--- Example 1 ---
REF : මේ අයුරින් මරණයට පත් වේ
PRED: මේ අයුරින් මරණයට පත් වේ

--- Example 2 ---
REF : ඒකට මොකද මේකෙන්
PRED: ඒකට මොකද මේකෙන්